CREATE OR ALTER PROCEDURE sp_CustomerAccounts
@param_Start_Date_Source DATETIME= NULL
,@param_End_Date_Source DATETIME= NULL
,@param_Is_Deleted BIT =NULL
,@param_Client_Id INT = NULL
,@param_Customer_Name VARCHAR(25) = NULL
,@param_Customer_LastName VARCHAR(25)=NULL
,@param_CustomerAccountId INT = NULL

AS
BEGIN
	BEGIN TRY

		DECLARE @SQL NVARCHAR(4000)
		SET @SQL=''
		DECLARE @local_start INT
		SET @local_start = 0
			
			IF((@param_Start_Date_Source IS NOT NULL AND @param_End_Date_Source IS NOT NULL) OR (@param_Start_Date_Source IS NOT NULL AND @param_End_Date_Source IS NULL) OR (@param_Start_Date_Source IS NULL AND @param_End_Date_Source IS NOT NULL) AND @local_start=0)
			BEGIN 
				SET @local_start = 1
			END
			IF(@param_Is_Deleted IS NOT NULL AND @local_start=0)
			BEGIN 
				SET @local_start = 2
			END
			IF(@param_Client_Id IS NOT NULL AND @local_start=0)
			BEGIN 
				SET @local_start = 3
			END
			IF(@param_Customer_Name IS NOT NULL AND @local_start=0)
			BEGIN 
				SET @local_start = 4
			END
			IF(@param_Customer_LastName IS NOT NULL AND @local_start=0)
			BEGIN 
				SET @local_start = 5
			END
			IF(@param_CustomerAccountId IS NOT NULL AND @local_start=0)
			BEGIN 
				SET @local_start = 6
			END


			--CUSTOMER DATE SOURCE
			IF (@param_Start_Date_Source IS NOT NULL OR @param_End_Date_Source IS NOT NULL AND (EXISTS(SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE LAST_MODIFIED_DATE > @param_Start_Date_Source AND LAST_MODIFIED_DATE < @param_End_Date_Source)))
			BEGIN
				IF(@param_End_Date_Source IS NULL)
				BEGIN
					SET @SQL = @SQL + 'SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE LAST_MODIFIED_DATE >= '+ ''''+CAST(@param_Start_Date_Source AS VARCHAR)+''''
				END
				IF(@param_Start_Date_Source IS NULL)
				BEGIN
					SET @SQL = @SQL + 'SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE LAST_MODIFIED_DATE <= '+ ''''+CAST(@param_End_Date_Source AS VARCHAR)+''''
				END
				IF(@param_Start_Date_Source IS NOT NULL AND @param_End_Date_Source IS NOT NULL)
				BEGIN
					SET @SQL = @SQL + 'SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE LAST_MODIFIED_DATE >= '+ ''''+CAST(@param_Start_Date_Source AS VARCHAR)+'''' +'AND LAST_MODIFIED_DATE <= '+ ''''+CAST(@param_End_Date_Source AS VARCHAR)+''''
				END
			END
			--CUSTOMER IS DELETED
			IF (@param_Is_Deleted IS NOT NULL AND (EXISTS(SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE IS_DELETED = @param_Is_Deleted)))
			BEGIN
				IF @local_start != 2
				BEGIN
					SET @SQL = @SQL + 'INTERSECT '
				END
					SET @SQL = @SQL + 'SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE IS_DELETED = '+ CAST(@param_Is_Deleted AS VARCHAR)
					PRINT @SQL
			END


			--CLIENT ID
			IF (@param_Client_Id IS NOT NULL AND (EXISTS(SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE CLIENT_ID = @param_Client_Id)))
			BEGIN
				IF @local_start != 3
				BEGIN
					SET @SQL = @SQL + 'INTERSECT '
				END
					SET @SQL = @SQL + 'SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE CLIENT_ID = '+ ''''+CAST(@param_Client_Id AS VARCHAR)+''''
			END
			--CUSTOMER NAME
			IF (@param_Customer_Name IS NOT NULL AND (EXISTS(SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE CUSTOMER_NAME = @param_Customer_Name)))
			BEGIN
				IF @local_start != 4
				BEGIN
					SET @SQL = @SQL + 'INTERSECT '
				END
					SET @SQL = @SQL + 'SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE CUSTOMER_NAME = '+ ''''+@param_Customer_Name+''''
			END
			--CUSTOMER LAST NAME
			IF (@param_Customer_LastName IS NOT NULL AND (EXISTS(SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE CUSTOMER_LAST_NAME = @param_Customer_LastName)))
			BEGIN
				IF @local_start != 5
				BEGIN
					SET @SQL = @SQL + 'INTERSECT '
				END
					SET @SQL = @SQL + 'SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE CUSTOMER_LAST_NAME = '+ ''''+@param_Customer_LastName+''''
			END
			--CUSTOMER ACCOUNT ID
			IF (@param_CustomerAccountId IS NOT NULL AND (EXISTS(SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE CUSTOMER_ACCOUNT_ID = @param_CustomerAccountId)))
			BEGIN
			IF @local_start != 6
				BEGIN
					SET @SQL = @SQL + 'INTERSECT '
				END
				SET @SQL = @SQL + 'SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE CUSTOMER_ACCOUNT_ID = '+ CAST(@param_CustomerAccountId AS VARCHAR)
			END
			
				EXEC(@SQL)
				
	END TRY

	BEGIN CATCH
		PRINT 'N'+ @@ERROR	
	END CATCH
END