CREATE OR ALTER PROCEDURE sp_CustomerAccounts
@param_CustomerAccountId INT = NULL
,@param_Client_Id INT = NULL
,@param_Customer_Name VARCHAR(25) = NULL
,@param_Customer_LastName VARCHAR(25)=NULL
,@param_Is_Deleted BIT =NULL
,@param_Start_Date_Source DATETIME= NULL
,@param_End_Date_Source DATETIME= NULL
AS
BEGIN
	BEGIN TRY

		DECLARE @SQL NVARCHAR(4000)
		SET @SQL=''
		DECLARE @local_start BIT
		SET @local_start = 0
			--CUSTOMER ACCOUNT ID
			IF (@param_CustomerAccountId IS NOT NULL AND (EXISTS(SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE CUSTOMER_ACCOUNT_ID = @param_CustomerAccountId)))
			BEGIN
				SET @SQL = @SQL + 'SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE CUSTOMER_ACCOUNT_ID = '+ ''''+CAST(@param_CustomerAccountId AS NVARCHAR(10))+''''
			END

			--CLIENT ID
			IF (@param_Client_Id IS NOT NULL AND (EXISTS(SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE CLIENT_ID = @param_Client_Id)))
			BEGIN
				SET @SQL = @SQL + 'INTERSECT '
				SET @SQL = @SQL + 'SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE CUSTOMER_ACCOUNT_ID = '+ ''''+CAST(@param_Client_Id AS NVARCHAR(10))+''''
			END

			--CUSTOMER NAME
			IF (@param_Customer_Name IS NOT NULL AND (EXISTS(SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE CUSTOMER_NAME = @param_Customer_Name)))
			BEGIN
				PRINT 'ENTRA'
				SET @SQL = @SQL + 'INTERSECT '
				SET @SQL = @SQL + 'SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE CUSTOMER_NAME = '+ ''''+CAST(@param_Customer_Name AS NVARCHAR(10))+''''
			END

			--CUSTOMER LAST NAME
			IF (@param_Customer_LastName IS NOT NULL AND (EXISTS(SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE CUSTOMER_LAST_NAME = @param_Customer_LastName)))
			BEGIN
				SET @SQL = @SQL + 'INTERSECT '
				SET @SQL = @SQL + 'SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE CUSTOMER_LAST_NAME = '+ ''''+CAST(@param_Customer_LastName AS NVARCHAR(10))+''''
			END

			--CUSTOMER IS DELETED
			IF (@param_Is_Deleted IS NOT NULL AND (EXISTS(SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE IS_DELETED = @param_Is_Deleted)))
			BEGIN
				SET @SQL = @SQL + 'INTERSECT '
				SET @SQL = @SQL + 'SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE IS_DELETED = '+ ''''+CAST(@param_Is_Deleted AS NVARCHAR(10))+''''
			END
			
			--CUSTOMER DATE SOURCE
			IF (@param_CustomerAccountId IS NOT NULL AND (EXISTS(SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE LAST_MODIFIED_DATE > @param_Start_Date_Source AND  LAST_MODIFIED_DATE < @param_End_Date_Source)))
			BEGIN
				SET @SQL = @SQL + 'INTERSECT '
				SET @SQL = @SQL + 'SELECT CUSTOMER_ACCOUNT_ID, CLIENT_ID, CUSTOMER_NAME, CUSTOMER_LAST_NAME, IS_DELETED, LAST_MODIFIED_DATE FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE CUSTOMER_ACCOUNT_ID > '+ ''''+CAST(@param_CustomerAccountId AS NVARCHAR(10))+'''' +'AND CUSTOMER_ACCOUNT_ID < '+ ''''+CAST(@param_CustomerAccountId AS NVARCHAR(10))+''''
			END

				PRINT @SQL
				EXEC(@SQL)

	END TRY

	BEGIN CATCH
		PRINT 'N'+ @@ERROR	
	END CATCH
END
